name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: ./.github/workflows/single-tests.yml
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  tests_oldest:
    uses: ./.github/workflows/single-tests-oldest.yml
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
